"""Score predictions against ground truth using a Chemprop splits file.

Assumptions:
- You have a prediction CSV (e.g., from `chemprop predict`) that was generated by
  predicting on the *same CSV* you pass as --data-csv (so rows align).
- You have a Chemprop splits file JSON list of objects with train/val/test
  indices (0-based).

Metrics:
- MAE
- RAE (Relative Absolute Error), using a train-mean baseline for the denominator
- R2
- Spearman rho
- Kendall tau
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd
from scipy import stats


def mae(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    return float(np.mean(np.abs(y_true - y_pred)))


def r2(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    ss_res = float(np.sum((y_true - y_pred) ** 2))
    ss_tot = float(np.sum((y_true - float(np.mean(y_true))) ** 2))
    return float("nan") if ss_tot == 0 else 1.0 - ss_res / ss_tot


def rae(y_true: np.ndarray, y_pred: np.ndarray, baseline: float) -> float:
    num = float(np.sum(np.abs(y_true - y_pred)))
    den = float(np.sum(np.abs(y_true - baseline)))
    return float("nan") if den == 0 else num / den


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--data-csv", type=Path, required=True)
    ap.add_argument("--preds-csv", type=Path, required=True)
    ap.add_argument("--splits-file", type=Path, required=True)
    ap.add_argument(
        "--split-idx",
        type=int,
        default=0,
        help="Which split entry to use from the splits JSON list (default: 0)",
    )
    ap.add_argument("--smiles-col", type=str, default="SMILES")
    ap.add_argument("--name-col", type=str, default="Molecule Name")
    ap.add_argument("--target-col", type=str, default="pEC50")
    ap.add_argument(
        "--out-json",
        type=Path,
        default=None,
        help="Optional path to write metrics as JSON.",
    )
    args = ap.parse_args()

    df = pd.read_csv(args.data_csv)
    preds = pd.read_csv(args.preds_csv)

    if len(df) != len(preds):
        raise SystemExit(
            f"Row count mismatch: data has {len(df)} rows, preds has {len(preds)} rows. "
            "Score script assumes predictions were generated on the same CSV." 
        )

    # Basic alignment checks.
    if args.smiles_col in df.columns and args.smiles_col in preds.columns:
        if not df[args.smiles_col].astype(str).reset_index(drop=True).equals(
            preds[args.smiles_col].astype(str).reset_index(drop=True)
        ):
            raise SystemExit("SMILES column does not align between --data-csv and --preds-csv")
    if args.name_col in df.columns and args.name_col in preds.columns:
        if not df[args.name_col].astype(str).reset_index(drop=True).equals(
            preds[args.name_col].astype(str).reset_index(drop=True)
        ):
            raise SystemExit("Molecule Name column does not align between --data-csv and --preds-csv")

    if args.target_col not in df.columns:
        raise SystemExit(f"--data-csv missing target column {args.target_col!r}")
    if args.target_col not in preds.columns:
        raise SystemExit(f"--preds-csv missing prediction column {args.target_col!r}")

    splits = json.loads(args.splits_file.read_text())
    if not isinstance(splits, list) or not splits:
        raise SystemExit("splits-file must be a JSON list with at least one split")
    if args.split_idx < 0 or args.split_idx >= len(splits):
        raise SystemExit(f"--split-idx out of range: {args.split_idx} (len={len(splits)})")

    split = splits[args.split_idx]
    train_idx = np.asarray(split.get("train", []), dtype=int)
    val_idx = np.asarray(split.get("val", []), dtype=int)

    if train_idx.size == 0 or val_idx.size == 0:
        raise SystemExit("split must contain non-empty 'train' and 'val' indices")

    y = df[args.target_col].astype(float).to_numpy()
    yhat = preds[args.target_col].astype(float).to_numpy()

    y_train = y[train_idx]
    yhat_train = yhat[train_idx]
    y_val = y[val_idx]
    yhat_val = yhat[val_idx]

    # Handle multitask CSVs: many rows may have NaN labels for the target task.
    train_mask = (~np.isnan(y_train)) & (~np.isnan(yhat_train))
    val_mask = (~np.isnan(y_val)) & (~np.isnan(yhat_val))

    y_train_l = y_train[train_mask]
    y_val_l = y_val[val_mask]
    yhat_val_l = yhat_val[val_mask]

    baseline = float(np.mean(y_train_l)) if y_train_l.size else float("nan")

    # Correlations (require at least 2 points)
    if y_val_l.size >= 2:
        sp = stats.spearmanr(y_val_l, yhat_val_l)
        kt = stats.kendalltau(y_val_l, yhat_val_l)
        sp_rho = float(sp.correlation) if sp is not None else float("nan")
        kt_tau = float(kt.correlation) if kt is not None else float("nan")
    else:
        sp_rho = float("nan")
        kt_tau = float("nan")

    metrics = {
        "n_train": int(train_idx.size),
        "n_val": int(val_idx.size),
        "n_train_labeled": int(y_train_l.size),
        "n_val_labeled": int(y_val_l.size),
        "mae": mae(y_val_l, yhat_val_l) if y_val_l.size else float("nan"),
        "rae": rae(y_val_l, yhat_val_l, baseline=baseline) if y_val_l.size else float("nan"),
        "r2": r2(y_val_l, yhat_val_l) if y_val_l.size else float("nan"),
        "spearman_rho": sp_rho,
        "kendall_tau": kt_tau,
        "baseline_train_mean": baseline,
    }

    print(json.dumps(metrics, indent=2, sort_keys=True))

    if args.out_json is not None:
        args.out_json.parent.mkdir(parents=True, exist_ok=True)
        args.out_json.write_text(json.dumps(metrics, indent=2, sort_keys=True))
        print(f"Wrote metrics to {args.out_json}")


if __name__ == "__main__":
    main()
